#!/bin/bash

if [ -z $1 ]; then
    echo "usage : $0 inputfile"
    exit 0
fi

CMDLINE=`which m4`

echo "# autogenerated" > conf.m4
while read line;do
    name=`echo $line | cut -d'=' -f1`
    val=`echo $line | cut -d'=' -f2`
    [ ! -z $name ] && echo "define(\`$name', \`$val')" >> conf.m4    
done < autoslack.conf

CMDLINE=$CMDLINE" $1"

. autoslack.conf

$CMDLINE > $AS_CFG_PRGNAM.SlackBuild

echo "generated $AS_CFG_PRGNAM.SlackBuild"
