include(autoslack.m4)

AS_HEADER(AS_CFG_PRGNAM, AS_CFG_VERSION, AS_CFG_AUTHOR, AS_CFG_EMAIL)

AS_LICENSE_SLACKWARE(AS_CFG_AUTHOR, AS_CFG_EMAIL)

AS_VARS(AS_CFG_PRGNAM, AS_CFG_VERSION)

AS_CHECK_SLACKDESC

set -e

AS_DOWNLOAD(AS_CFG_DOWNLOAD, AS_CFG_TAREXT)

AS_PREPARE(AS_CFG_TAREXT)

AS_CONFIGURE

make
make install DESTDIR=$PKG

AS_STRIP

AS_COPY_DOCS(AS_CFG_DOC)

AS_MAKEPKG
