include(autoslack.m4)

AS_SLACKDESK_HELP
AS_SLACKDESK_RULER
AS_CFG_PRGNAM:
AS_CFG_PRGNAM:
AS_CFG_PRGNAM:
AS_CFG_PRGNAM:
AS_CFG_PRGNAM:
AS_CFG_PRGNAM:
AS_CFG_PRGNAM:
AS_CFG_PRGNAM:
AS_CFG_PRGNAM:	AC_CFG_HOMEPAGE
AS_CFG_PRGNAM:
AS_CFG_PRGNAM:
